version: "3.9"

services:
  db:
    image: postgres:15
    container_name: medicare_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medicare
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: medicare_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload

volumes:
  postgres_data:
